packages:
  - "hello-world"
  - "hello-mcp"
  - "mode-mcp"
  - "react-todo-app"
  - "hello-RAG"
  - "hello-RAG-Loader"
  - "hello-milvus"
  - "hello-RAG-dfzqdoc"
  - "hello-outputparser"
  - "hello-runnabled"
  - "hello-nest-langchain"
allowBuilds:
  esbuild: true
  protobufjs: true
  unrs-resolver: true
